name: flutter_node_auth
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^4.2.1
  get: ^4.3.8
  dio: ^4.0.0
  image_picker: ^0.8.4+2
  image_cropper: ^1.4.1
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.1.0
  pull_to_refresh: ^2.0.0
  google_mobile_ads: ^0.13.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/

  
  

  
  

 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
